#pragma once

#include <crtdbg.h>
#include <windows.h>
#include <windowsx.h>
#include <wrl.h>
#include <dxgi1_4.h>
#include <d3d12.h>
#include <D3Dcompiler.h>
#include <DirectXMath.h>
#include <DirectXPackedVector.h>
#include <DirectXColors.h>
#include <DirectXCollision.h>
#include <string>
#include <memory>
#include <algorithm>
#include <vector>
#include <array>
#include <unordered_map>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <cassert>
#include <comdef.h>
#include <float.h>
#include <cmath>
#include "../FuChenEngine/Common/d3dx12.h"

#include "d3dUtil.h"
#include "GameTimer.h"
#include "MathHelper.h"
#include "UploadBuffer.h"